; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env_common]
platform = espressif32
framework = arduino
monitor_speed = 115200
build_flags = 
	-std=gnu99
	-std=c++17
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DCONFIG_ESP32_DISABLE_BROWNOUT_DETECTOR
	-DUSER_SETUP_LOADED=1
	-DLOAD_GLCD=1
	-DLOAD_FONT2=1
	-DLOAD_FONT4=1
lib_deps = 
	bitbank2/PNGdec@^1.1.0
	adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	bblanchon/ArduinoJson@^7.4.1
	mikalhart/TinyGPSPlus@^1.1.0
	h2zero/NimBLE-Arduino@^1.4.2
	dfrobot/DFRobot_QMC5883@^1.0.0

[env:esp32-universal]
platform = ${env_common.platform}
board = esp-wrover-kit
framework = ${env_common.framework}
monitor_speed = ${env_common.monitor_speed}
board_build.partitions = partitions_custom.csv
build_flags = ${env_common.build_flags}
	-DGPS_BAUD=115200
	-DGPS_DEFAULT_BAUD=115200
	-DDEVICE_HW_NAME=\"ESP32-WROVER-IE\"
	-DNAVION_VARIANT=\"navion.v1\"
	-DTFT_BL=5
	-DTFT_CS=25
	-DTFT_DC=26
	-DTFT_RST=19
	-DTFT_MOSI=23
	-DTFT_SCLK=18
	-DTFT_MISO=-1
	-DST7735_DRIVER
	-DTFT_RGB_ORDER=TFT_BGR
	-DTFT_WIDTH=128
	-DTFT_HEIGHT=160
	-DST7735_BLACKTAB
	-DSDMMC_CLK=14
	-DSDMMC_CMD=15
	-DSDMMC_D0=2
	-DSDMMC_D1=4
	-DSDMMC_D2=12
	-DSDMMC_D3=13
	-DSDMMC_MODE_1BIT=0
	-DI2C_SDA=21
	-DI2C_SCL=22
	-DDRDY_PIN=35
	-DOPADC_PIN=36
	-DFBADC_PIN=33
	-DBACKLIGHT_PWM_FREQ=5000
	-DBACKLIGHT_PWM_CHAN=0
	-DBACKLIGHT_PWM_RES=8
	-DBACKLIGHT_ACTIVE_LOW=0
	-DAUTO_BRIGHTNESS_DEFAULT=0
	-DFLASH_SIZE_MB=4
	-DDISABLE_GPS
lib_deps = ${env_common.lib_deps}

[env:esp32-s3-wroom-1]
platform = ${env_common.platform}
board = esp32-s3-devkitc-1
framework = ${env_common.framework}
monitor_speed = ${env_common.monitor_speed}
upload_speed = 115200
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions_16mb.csv
build_unflags = 
	-mfix-esp32-psram-cache-issue
build_flags = ${env_common.build_flags}
	-DFLASH_SIZE_MB=16
	-DGPS_BAUD=115200
	-DGPS_DEFAULT_BAUD=9600
	-DDEVICE_HW_NAME=\"ESP32-S3-WROOM-1\"
	-DNAVION_VARIANT=\"navion.v2\"
	-DUSE_GPS_UART1
	-DGPS_TX_PIN=48
	-DGPS_RX_PIN=47
	-DTFT_BL=3
	-DTFT_CS=38
	-DTFT_DC=19
	-DTFT_RST=1
	-DTFT_MOSI=11
	-DTFT_SCLK=12
	-DTFT_MISO=-1
	-DST7735_DRIVER
	-DTFT_RGB_ORDER=TFT_RGB
	-DTFT_WIDTH=128
	-DTFT_HEIGHT=160
	-DST7735_GREENTAB
	-DTFT_INVERSION_OFF
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=20000000
	-DSDMMC_CLK=8
	-DSDMMC_CMD=6
	-DSDMMC_D0=7
	-DSDMMC_D1=15
	-DSDMMC_D2=4
	-DSDMMC_D3=5
	-DSDMMC_MODE_1BIT=0
	-DI2C_SDA=17
	-DI2C_SCL=16
	-DDRDY_PIN=2
	-DOPADC_PIN=21
	-DFBADC_PIN=18
	-DALADC_PIN=20
	-DBACKLIGHT_PWM_FREQ=1000
	-DBACKLIGHT_PWM_CHAN=0
	-DBACKLIGHT_PWM_RES=8
	-DBACKLIGHT_ACTIVE_LOW=1
	-DAUTO_BRIGHTNESS_LDR_INVERT=1
lib_deps = 
	${env_common.lib_deps}
	gerhardmalan/QMC6310 Unified@^4.0.0
